[package]
name = "rvv-prototype-example"
version = "0.1.0"
edition = "2018"

[dependencies]
rvv = { path = "../rvv" }
uint = { version = "0.9.1", default-features = false }
ckb-std = "0.9.0"

[features]
default = []
simulator = ["rvv/simulator"]