[package]
name = "rvv-prototype-example"
version = "0.1.0"
edition = "2018"

[dependencies]
rvv = { path = "../rvv" }
ethereum-types = { version = "0.12.1", default-features = false, optional = true }
ckb-std = "0.9.0"

[features]
default = []
simulator = ["rvv/simulator", "ethereum-types"]